apiVersion: v1
kind: Service
metadata:
  name: website-testing
  namespace: configure-website
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: website-testing
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000