name: website-testing

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

env:
  ACR_RESOURCE_GROUP: drootwebsitestorage
  AZURE_CONTAINER_REGISTRY: websitedroot
  CLUSTER_NAME: aks-demo
  CLUSTER_RESOURCE_GROUP: drootwebsitestorage
  CONTAINER_NAME: demo-testing-1716809875858
  DEPLOYMENT_MANIFEST_PATH: |
    manifests/deployment.yaml
    manifests/service.yaml

jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure CLI
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Build and push image to ACR
        run: |
          az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY }}
          az acr build --image ${{ env.CONTAINER_NAME }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.ACR_RESOURCE_GROUP }} -f Dockerfile .

  deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs:
      - buildImage
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure CLI
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - uses: azure/use-kubelogin@v1.4.1
        name: Set up kubelogin for non-interactive login
        with:
          kubelogin-version: v0.0.27

      - uses: azure/aks-set-context@v3.1.0
        name: Get K8s context
        with:
          admin: "false"
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
          use-kubelogin: "true"

      - uses: azure/k8s-deploy@v4.1.3
        name: Deploy application
        with:
          action: deploy
          images: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
          manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
          namespace: configure-website


